import enum


class TournamentStatusENUM(enum.Enum):
    COMPLETED = "COMPLETED"
    CANCELED = "CANCELED"
    PROGRESS = "PROGRESS"
    REGISTRATION_OPEN = "REGISTRATION_OPEN"
    REGISTRATION_CLOSE = "REGISTRATION_CLOSE"
    SCHEDULED = "SCHEDULED"


class GridTypeENUM(enum.Enum):
    CIRCLE = "CIRCLE"
    PLAYOFF = "PLAYOFF"
