"""add grid tables

Revision ID: ac08ccfec4d0
Revises: f2a6ee4e368a
Create Date: 2024-07-18 22:52:19.225979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac08ccfec4d0'
down_revision: Union[str, None] = 'f2a6ee4e368a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('round',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('game_count', sa.Integer(), nullable=False),
    sa.Column('grid_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['grid_id'], ['grid.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grid_match_number', sa.Integer(), nullable=False),
    sa.Column('queue_match_number', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.UUID(), nullable=False),
    sa.Column('players_id', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('score', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('winner_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['round.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.ARRAY(sa.Integer()), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    op.drop_table('match')
    op.drop_table('round')
    # ### end Alembic commands ###
