"""add third place match

Revision ID: dbaa3614375a
Revises: 45c62920b76f
Create Date: 2024-07-23 14:24:38.578272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbaa3614375a'
down_revision: Union[str, None] = '45c62920b76f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grid', sa.Column('third_place_match', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grid', 'third_place_match')
    # ### end Alembic commands ###
